# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sonarqubeScan:
       runs-on: ubuntu-latest
       
       steps:
        - uses: actions/checkout@master
        - name: Build with Maven
          run: mvn -s settings.xml sonar:sonar \
            -Dsonar.projectKey=test1 \
            -Dsonar.login=3bef7eae5da373b508c1713b93de9eacad49ef10




        

          
 
