# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sonarqubeScan:
       runs-on: ubuntu-latest
       
       steps:
        - uses: actions/checkout@master
        - name: Build with Maven
          run: |
            mvn clean package sonar:sonar \
            -Dsonar.projectKey=githubEvaluation \
            -Dsonar.host.url=http://ec2-54-76-26-25.eu-west-1.compute.amazonaws.com:9000 \
            -Dsonar.login=5ec26240f69b2f236a7ab1ce269e70729749e893 \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.binaries=target/classes 


        

          
 
