# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI-CD PIPELINE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2     
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Run Tests
      run: mvn clean test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
          files: target/**/*.xml  
    - name: Build with Maven
      run: |
            mvn package sonar:sonar \
            -Dsonar.projectKey=githubEvaluation \
            -Dsonar.host.url=http://ec2-34-250-134-170.eu-west-1.compute.amazonaws.com:9000 \
            -Dsonar.login=5ec26240f69b2f236a7ab1ce269e70729749e893 \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.binaries=target/classes 
 
                  
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
  
    
    - name: Setup docker
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: bdzanko17
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: test
      run: ls
    - name: Build and push
      id: docker_build  
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bdzanko17/testnaaplikacija:latest
        
  deploy:
       runs-on: ubuntu-latest
       needs: build
       steps:
           - name: multiple command
             uses: appleboy/ssh-action@master
             with:
                host: ec2-34-250-134-170.eu-west-1.compute.amazonaws.com
                username: ec2-user
                key: ${{ secrets.KEY }}
                script: |
                  docker run -p 8080:8080 -d bdzanko17/testnaaplikacija:latest

   

  

        

          
 
