# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: 20.52.216.40
        username: azureuser
        key: ${{ secrets.KEY }}
        script: |
          whoami
          ls -al
          docker ps

